name: VIB
on: # rebuild any PRs and main branch changes
  pull_request:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
    branches: ["**"]
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com
jobs:
  vib-container:
    runs-on: ubuntu-latest
    name: Package Container
    steps:
      - uses: actions/checkout@v2
        name: Checkout Java-lib Repository
        with:
          ref: dev-proxy2
          repository: wavefrontHQ/java-lib
      - name: Build Java-lib
        run: mvn --batch-mode install
      - uses: actions/checkout@v2
        name: Checkout Proxy Repository
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: build application
        run: USER=${{ secrets.DOCKER_USER }} DOCKER_TAG=gh-build MVN_ARGS=-DskipTests make build-jar docker
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USER }}/proxy-dev:gh-build
      - uses: vmware-labs/vmware-image-builder-action@main
        name: Package Wavefront container
        with:
          pipeline: vib-container.json
        env:
          VIB_ENV_DOCKER_USER: ${{ secrets.DOCKER_USER }}
  tests-chain-checking:
    runs-on: ubuntu-latest
    needs: vib-container
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: vmware-labs/vmware-image-builder-action@main
        name: Verify Wavefront container
        with:
          pipeline: vib-chain-checking.json
  tests-multi-tenant:
    runs-on: ubuntu-latest
    needs: vib-container
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: vmware-labs/vmware-image-builder-action@main
        name: Verify Wavefront multi-tenant
        with:
          pipeline: vib-multi-tenant.json
  # tests-buffer-lock:
  #   runs-on: ubuntu-latest
  #   needs: vib-container
  #   steps:
  #     - uses: actions/checkout@v2
  #       name: Checkout Repository
  #       with:
  #         ref: ${{ github.event.pull_request.head.ref }}
  #         repository: ${{ github.event.pull_request.head.repo.full_name }}
  #     - uses: vmware-labs/vmware-image-builder-action@main
  #       name: Verify Wavefront container
  #       with:
  #         pipeline: vib-buffer-lock.json
  # tests-debian:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       name: Checkout Repository
  #       with:
  #         ref: ${{ github.event.pull_request.head.ref }}
  #         repository: ${{ github.event.pull_request.head.repo.full_name }}
  #     - uses: vmware-labs/vmware-image-builder-action@main
  #       name: Verify Wavefront container
  #       with:
  #         pipeline: vib-deb-package-debian.json
  vib-maven:
    runs-on: ubuntu-latest
    name: make build-jar
    steps:
      - uses: actions/checkout@v2
        name: Checkout Java-lib Repository
        with:
          ref: dev-proxy2
          repository: wavefrontHQ/java-lib
      - name: Build Java-lib
        run: mvn --batch-mode install
      - uses: actions/checkout@v2
        name: Checkout Proxy Repository
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: build application
        run: make build-jar
