name: VIB
on: # rebuild any PRs and main branch changes
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
    branches: ["**"]
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ["11"]
        # java: ["11", "16", "17"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"
          cache: maven
  vib-container:
    runs-on: ubuntu-latest
    name: Package Container
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: vmware-labs/vmware-image-builder-action@main
        name: Package Wavefront container
        with:
          pipeline: vib-container.json
        env:
          VIB_ENV_HARBOR_REGISTRY_PASSWORD: ${{ secrets.HARBOR_REGISTRY_PASSWORD }}
          VIB_ENV_DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
  vib-verify:
    runs-on: ubuntu-latest
    needs: vib-container
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: vmware-labs/vmware-image-builder-action@main
        name: Verify Wavefront container
        with:
          pipeline: vib-verify.json
